#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# slstatus Bar
#/usr/local/bin/slstatus &

#Compositor
compton -b &
#picom -CG --no-fading-openclose &


#loop 
#while xsetroot -name "`date` `uptime | sed 's/.*,//'`"
#do
#	sleep 1
#done &

~/video.sh

xrandr --output Virtual1 --mode 1920x1080_60.00

# Restore wallpaper
nitrogen --set-zoom-fill ~/Pictures/wallhaven-1920x1080.png 

/usr/local/bin/slstatus &

exec dwm


